# Generated by Django 3.2.6 on 2021-12-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
