# Generated by Django 3.2.6 on 2021-12-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='typeOfquestion',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Fill in the blanks', 'Fill in the blanks')], default=('MCQ', 'MCQ'), max_length=20),
        ),
    ]
