# Generated by Django 3.2.6 on 2021-12-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
