# Generated by Django 3.2.6 on 2022-01-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quizAccessTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
                ('subjects', models.CharField(max_length=150)),
                ('std', models.CharField(max_length=50)),
            ],
        ),
    ]
