# Generated by Django 3.2.6 on 2021-12-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regester', '0005_alter_profile1_std'),
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='std',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regester.profile1'),
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regester.profile1')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.subjects'),
        ),
    ]
