# Generated by Django 3.2.6 on 2021-12-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20211215_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('std', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('CET', 'CET'), ('JEE', 'JEE'), ('NEET', 'NEET'), ('Navodaya Vidyalaya', 'Navodaya Vidyalaya'), ('12 COMBO', '12COMBO')], default='', max_length=20)),
            ],
        ),
    ]
