# Generated by Django 3.2.6 on 2021-12-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0004_auto_20211215_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='std',
        ),
    ]
