# Generated by Django 4.0.2 on 2022-06-16 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_remove_quiz_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.subjects1', verbose_name='Subject-Class'),
        ),
    ]
