# Generated by Django 3.2.6 on 2021-12-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regester', '0003_alter_profile1_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
