# Generated by Django 3.2.6 on 2021-12-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regester', '0005_alter_profile1_std'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='std',
            field=models.CharField(choices=[('0', '0'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('CET', 'CET'), ('JEE', 'JEE'), ('NEET', 'NEET'), ('Navodaya Vidyalaya', 'Navodaya Vidyalaya'), ('12 COMBO', '12COMBO')], default='', max_length=20),
        ),
    ]
