# Generated by Django 3.2.6 on 2022-01-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regester', '0006_alter_profile1_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile1',
            name='ref_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
