# Generated by Django 3.2.6 on 2022-01-10 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regester', '0008_auto_20220109_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile1',
            old_name='ref_points',
            new_name='reward_points',
        ),
    ]
