# Generated by Django 4.0.2 on 2022-09-04 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regester', '0009_rename_ref_points_profile1_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile1',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
