# Generated by Django 4.0.2 on 2022-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_check_attend_attendancetable_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancetable',
            name='present',
        ),
        migrations.AddField(
            model_name='attendancetable',
            name='attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=15, null=True),
        ),
    ]
